version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: runtime
      args:
        USERNAME: vscode
        USER_UID: 1000
        USER_GID: 1000
      cache_from:
        - dotfiles-devcontainer:latest
        - dotfiles-devcontainer:base-deps
        - dotfiles-devcontainer:tools-cache
    
    volumes:
      # Mount workspace
      - ..:/workspaces/dotfiles:cached
      
      # Persistent volumes for better performance
      - vscode-server:/home/vscode/.vscode-server
      - mise-cache:/home/vscode/.cache/mise
      - node-modules-cache:/home/vscode/.cache/npm
      - python-cache:/home/vscode/.cache/pip
    
    environment:
      - MISE_DATA_DIR=/home/vscode/.local/share/mise
      - SHELL=/bin/zsh
    
    user: vscode
    working_dir: /workspaces/dotfiles
    
    # Keep container running
    command: sleep infinity
    
    # Better resource limits
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  vscode-server:
    name: dotfiles-vscode-server
  mise-cache:
    name: dotfiles-mise-cache
  node-modules-cache:
    name: dotfiles-node-cache
  python-cache:
    name: dotfiles-python-cache
